### ISSUE TITLE
Crashed my site

### ISSUE THREAD

**Issue by socialspark** [eventespresso/eea-beaver-builder#12]
I've got the latest version of BB 2.0.6, and EE 4.9.58p. When I installed this plugin it gave me this error: https://www.screencast.com/t/dBkH1vvPD. I'm also using Beaver Themer. I used my staging site, so no harm, just thought you should know. I can live without the plugin for now, but would love to see more features added.

Thanks.

**Comment by sethshoultes** [comment]
Hi there!

Thanks for reporting the issue. However, a 500 error is a general Internal Server Error. Would it be possible to turn on WP Debug? Hopefully, that will give us a more informative error.

**Comment by socialspark** [comment]
Thanks for getting back to me. I’m on vacation next week, so it might be
awhile before I get a chance to try WP Debug, but I’ll give it a shot.


Have you tried the Builder with EE yet? BB Support told me it didn’t look
like EE used custom fields so it wouldn’t work.


On March 8, 2018 at 8:56:13 PM, Seth (notifications@github.com) wrote:

Hi there!

Thanks for reporting the issue. However, a 500 error is a general Internal
Server Error. Would it be possible to turn on WP Debug? Hopefully, that
will give us a more informative error.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/eventespresso/eea-beaver-builder/issues/12#issuecomment-371687770>,
or mute the thread
