### ISSUE TITLE
Tickets widget not appearing until page saved

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-beaver-builder#5]
This has been happening since #4 got fixed

**Comment by mnelson4** [comment]
Seth was going to get credentials so we could ask about this in their support forum

**Comment by mnelson4** [comment]
Using the callback instead of a dynamically created list solved the issue alright! @sethshoultes can you please double-check to verify this issue is solved, and there is no regression with #4

**Comment by sethshoultes** [comment]
Verified the issue is resolved.
